/*
 * PortainerCE API
 *
 * Portainer API is an HTTP API served by Portainer. It is used by the Portainer UI and everything you can do with the UI can be done using the HTTP API. Examples are available at https://documentation.portainer.io/api/api-examples/ You can find out more about Portainer at [http://portainer.io](http://portainer.io) and get some support on [Slack](http://portainer.io/slack/).  # Authentication  Most of the API environments(endpoints) require to be authenticated as well as some level of authorization to be used. Portainer API uses JSON Web Token to manage authentication and thus requires you to provide a token in the **Authorization** header of each request with the **Bearer** authentication mechanism.  Example:  ``` Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsInJvbGUiOjEsImV4cCI6MTQ5OTM3NjE1NH0.NJ6vE8FY1WG6jsRQzfMqeatJ4vh2TWAeeYfDhP71YEE ```  # Security  Each API environment(endpoint) has an associated access policy, it is documented in the description of each environment(endpoint).  Different access policies are available:  - Public access - Authenticated access - Restricted access - Administrator access  ### Public access  No authentication is required to access the environments(endpoints) with this access policy.  ### Authenticated access  Authentication is required to access the environments(endpoints) with this access policy.  ### Restricted access  Authentication is required to access the environments(endpoints) with this access policy. Extra-checks might be added to ensure access to the resource is granted. Returned data might also be filtered.  ### Administrator access  Authentication as well as an administrator role are required to access the environments(endpoints) with this access policy.  # Execute Docker requests  Portainer **DO NOT** expose specific environments(endpoints) to manage your Docker resources (create a container, remove a volume, etc...).  Instead, it acts as a reverse-proxy to the Docker HTTP API. This means that you can execute Docker requests **via** the Portainer HTTP API.  To do so, you can use the `/endpoints/{id}/docker` Portainer API environment(endpoint) (which is not documented below due to Swagger limitations). This environment(endpoint) has a restricted access policy so you still need to be authenticated to be able to query this environment(endpoint). Any query on this environment(endpoint) will be proxied to the Docker API of the associated environment(endpoint) (requests and responses objects are the same as documented in the Docker API).  # Private Registry  Using private registry, you will need to pass a based64 encoded JSON string ‘{\"registryId\":\\<registryID value\\>}’ inside the Request Header. The parameter name is \"X-Registry-Auth\". \\<registryID value\\> - The registry ID where the repository was created.  Example:  ``` eyJyZWdpc3RyeUlkIjoxfQ== ```  **NOTE**: You can find more information on how to query the Docker API in the [Docker official documentation](https://docs.docker.com/engine/api/v1.30/) as well as in [this Portainer example](https://documentation.portainer.io/api/api-examples/).
 *
 * API version: 2.17.1
 * Contact: info@portainer.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

type PortainerTemplate struct {
	// Mandatory container/stack fields Template Identifier
	Id int32 `json:"Id,omitempty"`
	// Whether the template should be available to administrators only
	AdministratorOnly bool `json:"administrator_only,omitempty"`
	// A list of categories associated to the template
	Categories []string `json:"categories,omitempty"`
	// The command that will be executed in a container template
	Command string `json:"command,omitempty"`
	// Description of the template
	Description string `json:"description,omitempty"`
	// A list of environment(endpoint) variables used during the template deployment
	Env []PortainerTemplateEnv `json:"env,omitempty"`
	// Container hostname
	Hostname string `json:"hostname,omitempty"`
	// Mandatory container fields Image associated to a container template. Mandatory for a container template
	Image string `json:"image,omitempty"`
	// Whether the container should be started in interactive mode (-i -t equivalent on the CLI)
	Interactive bool `json:"interactive,omitempty"`
	// Container labels
	Labels []PortainerPair `json:"labels,omitempty"`
	// URL of the template's logo
	Logo string `json:"logo,omitempty"`
	// Optional stack/container fields Default name for the stack/container to be used on deployment
	Name string `json:"name,omitempty"`
	// Name of a network that will be used on container deployment if it exists inside the environment(endpoint)
	Network string `json:"network,omitempty"`
	// A note that will be displayed in the UI. Supports HTML content
	Note string `json:"note,omitempty"`
	// Platform associated to the template. Valid values are: 'linux', 'windows' or leave empty for multi-platform
	Platform string `json:"platform,omitempty"`
	// A list of ports exposed by the container
	Ports []string `json:"ports,omitempty"`
	// Whether the container should be started in privileged mode
	Privileged bool `json:"privileged,omitempty"`
	// Optional container fields The URL of a registry associated to the image for a container template
	Registry string `json:"registry,omitempty"`
	// Mandatory stack fields
	Repository *PortainerTemplateRepository `json:"repository,omitempty"`
	// Container restart policy
	RestartPolicy string `json:"restart_policy,omitempty"`
	// Mandatory Edge stack fields Stack file used for this template
	StackFile string `json:"stackFile,omitempty"`
	// Title of the template
	Title string `json:"title,omitempty"`
	// Template type. Valid values are: 1 (container), 2 (Swarm stack) or 3 (Compose stack)
	Type_ int32 `json:"type,omitempty"`
	// A list of volumes used during the container template deployment
	Volumes []PortainerTemplateVolume `json:"volumes,omitempty"`
}
