# Basic dependabot.yml file with
# minimum configuration for two package managers

version: 2
updates:
  # Enable version updates Golang
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
