/*
 * Docker Engine API
 *
 * The Engine API is an HTTP API served by Docker Engine. It is the API the Docker client uses to communicate with the Engine, so everything the Docker client can do can be done with the API.  Most of the client's commands map directly to API endpoints (e.g. `docker ps` is `GET /containers/json`). The notable exception is running containers, which consists of several API calls.  # Errors  The API uses standard HTTP status codes to indicate the success or failure of the API call. The body of the response will be JSON in the following format:  ``` {   \"message\": \"page not found\" } ```  # Versioning  The API is usually changed in each release, so API calls are versioned to ensure that clients don't break. To lock to a specific version of the API, you prefix the URL with its version, for example, call `/v1.30/info` to use the v1.30 version of the `/info` endpoint. If the API version specified in the URL is not supported by the daemon, a HTTP `400 Bad Request` error message is returned.  If you omit the version-prefix, the current version of the API (v1.42) is used. For example, calling `/info` is the same as calling `/v1.42/info`. Using the API without a version-prefix is deprecated and will be removed in a future release.  Engine releases in the near future should support this version of the API, so your client will continue to work even if it is talking to a newer Engine.  The API uses an open schema model, which means server may add extra properties to responses. Likewise, the server will ignore any extra query parameters and request body properties. When you write clients, you need to ignore additional properties in responses to ensure they do not break when talking to newer daemons.   # Authentication  Authentication for registries is handled client side. The client has to send authentication details to various endpoints that need to communicate with registries, such as `POST /images/(name)/push`. These are sent as `X-Registry-Auth` header as a [base64url encoded](https://tools.ietf.org/html/rfc4648#section-5) (JSON) string with the following structure:  ``` {   \"username\": \"string\",   \"password\": \"string\",   \"email\": \"string\",   \"serveraddress\": \"string\" } ```  The `serveraddress` is a domain/IP without a protocol. Throughout this structure, double quotes are required.  If you have already got an identity token from the [`/auth` endpoint](#operation/SystemAuth), you can just pass this instead of credentials:  ``` {   \"identitytoken\": \"9cbaf023786cd7...\" } ```
 *
 * API version: 1.42
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package docker

// Configuration for a network endpoint.
type EndpointSettings struct {
	IPAMConfig *EndpointIpamConfig `json:"IPAMConfig,omitempty"`
	Links      []string            `json:"Links,omitempty"`
	Aliases    []string            `json:"Aliases,omitempty"`
	// Unique ID of the network.
	NetworkID string `json:"NetworkID,omitempty"`
	// Unique ID for the service endpoint in a Sandbox.
	EndpointID string `json:"EndpointID,omitempty"`
	// Gateway address for this network.
	Gateway string `json:"Gateway,omitempty"`
	// IPv4 address.
	IPAddress string `json:"IPAddress,omitempty"`
	// Mask length of the IPv4 address.
	IPPrefixLen int32 `json:"IPPrefixLen,omitempty"`
	// IPv6 gateway address.
	IPv6Gateway string `json:"IPv6Gateway,omitempty"`
	// Global IPv6 address.
	GlobalIPv6Address string `json:"GlobalIPv6Address,omitempty"`
	// Mask length of the global IPv6 address.
	GlobalIPv6PrefixLen int64 `json:"GlobalIPv6PrefixLen,omitempty"`
	// MAC address for the endpoint on this network.
	MacAddress string `json:"MacAddress,omitempty"`
	// DriverOpts is a mapping of driver options and values. These options are passed directly to the driver and are driver specific.
	DriverOpts map[string]string `json:"DriverOpts,omitempty"`
}
