/*
 * Docker Engine API
 *
 * The Engine API is an HTTP API served by Docker Engine. It is the API the Docker client uses to communicate with the Engine, so everything the Docker client can do can be done with the API.  Most of the client's commands map directly to API endpoints (e.g. `docker ps` is `GET /containers/json`). The notable exception is running containers, which consists of several API calls.  # Errors  The API uses standard HTTP status codes to indicate the success or failure of the API call. The body of the response will be JSON in the following format:  ``` {   \"message\": \"page not found\" } ```  # Versioning  The API is usually changed in each release, so API calls are versioned to ensure that clients don't break. To lock to a specific version of the API, you prefix the URL with its version, for example, call `/v1.30/info` to use the v1.30 version of the `/info` endpoint. If the API version specified in the URL is not supported by the daemon, a HTTP `400 Bad Request` error message is returned.  If you omit the version-prefix, the current version of the API (v1.42) is used. For example, calling `/info` is the same as calling `/v1.42/info`. Using the API without a version-prefix is deprecated and will be removed in a future release.  Engine releases in the near future should support this version of the API, so your client will continue to work even if it is talking to a newer Engine.  The API uses an open schema model, which means server may add extra properties to responses. Likewise, the server will ignore any extra query parameters and request body properties. When you write clients, you need to ignore additional properties in responses to ensure they do not break when talking to newer daemons.   # Authentication  Authentication for registries is handled client side. The client has to send authentication details to various endpoints that need to communicate with registries, such as `POST /images/(name)/push`. These are sent as `X-Registry-Auth` header as a [base64url encoded](https://tools.ietf.org/html/rfc4648#section-5) (JSON) string with the following structure:  ``` {   \"username\": \"string\",   \"password\": \"string\",   \"email\": \"string\",   \"serveraddress\": \"string\" } ```  The `serveraddress` is a domain/IP without a protocol. Throughout this structure, double quotes are required.  If you have already got an identity token from the [`/auth` endpoint](#operation/SystemAuth), you can just pass this instead of credentials:  ``` {   \"identitytoken\": \"9cbaf023786cd7...\" } ```
 *
 * API version: 1.42
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package docker

// Information about an image in the local image cache.
type ImageInspect struct {
	// ID is the content-addressable ID of an image.  This identifier is a content-addressable digest calculated from the image's configuration (which includes the digests of layers used by the image).  Note that this digest differs from the `RepoDigests` below, which holds digests of image manifests that reference the image.
	Id string `json:"Id,omitempty"`
	// List of image names/tags in the local image cache that reference this image.  Multiple image tags can refer to the same image, and this list may be empty if no tags reference the image, in which case the image is \"untagged\", in which case it can still be referenced by its ID.
	RepoTags []string `json:"RepoTags,omitempty"`
	// List of content-addressable digests of locally available image manifests that the image is referenced from. Multiple manifests can refer to the same image.  These digests are usually only available if the image was either pulled from a registry, or if the image was pushed to a registry, which is when the manifest is generated and its digest calculated.
	RepoDigests []string `json:"RepoDigests,omitempty"`
	// ID of the parent image.  Depending on how the image was created, this field may be empty and is only set for images that were built/created locally. This field is empty if the image was pulled from an image registry.
	Parent string `json:"Parent,omitempty"`
	// Optional message that was set when committing or importing the image.
	Comment string `json:"Comment,omitempty"`
	// Date and time at which the image was created, formatted in [RFC 3339](https://www.ietf.org/rfc/rfc3339.txt) format with nano-seconds.
	Created string `json:"Created,omitempty"`
	// The ID of the container that was used to create the image.  Depending on how the image was created, this field may be empty.
	Container       string           `json:"Container,omitempty"`
	ContainerConfig *ContainerConfig `json:"ContainerConfig,omitempty"`
	// The version of Docker that was used to build the image.  Depending on how the image was created, this field may be empty.
	DockerVersion string `json:"DockerVersion,omitempty"`
	// Name of the author that was specified when committing the image, or as specified through MAINTAINER (deprecated) in the Dockerfile.
	Author string           `json:"Author,omitempty"`
	Config *ContainerConfig `json:"Config,omitempty"`
	// Hardware CPU architecture that the image runs on.
	Architecture string `json:"Architecture,omitempty"`
	// CPU architecture variant (presently ARM-only).
	Variant string `json:"Variant,omitempty"`
	// Operating System the image is built to run on.
	Os string `json:"Os,omitempty"`
	// Operating System version the image is built to run on (especially for Windows).
	OsVersion string `json:"OsVersion,omitempty"`
	// Total size of the image including all layers it is composed of.
	Size int64 `json:"Size,omitempty"`
	// Total size of the image including all layers it is composed of.  In versions of Docker before v1.10, this field was calculated from the image itself and all of its parent images. Docker v1.10 and up store images self-contained, and no longer use a parent-chain, making this field an equivalent of the Size field.  This field is kept for backward compatibility, but may be removed in a future version of the API.
	VirtualSize int64                 `json:"VirtualSize,omitempty"`
	GraphDriver *GraphDriverData      `json:"GraphDriver,omitempty"`
	RootFS      *ImageInspectRootFs   `json:"RootFS,omitempty"`
	Metadata    *ImageInspectMetadata `json:"Metadata,omitempty"`
}
