/*
 * Docker Engine API
 *
 * The Engine API is an HTTP API served by Docker Engine. It is the API the Docker client uses to communicate with the Engine, so everything the Docker client can do can be done with the API.  Most of the client's commands map directly to API endpoints (e.g. `docker ps` is `GET /containers/json`). The notable exception is running containers, which consists of several API calls.  # Errors  The API uses standard HTTP status codes to indicate the success or failure of the API call. The body of the response will be JSON in the following format:  ``` {   \"message\": \"page not found\" } ```  # Versioning  The API is usually changed in each release, so API calls are versioned to ensure that clients don't break. To lock to a specific version of the API, you prefix the URL with its version, for example, call `/v1.30/info` to use the v1.30 version of the `/info` endpoint. If the API version specified in the URL is not supported by the daemon, a HTTP `400 Bad Request` error message is returned.  If you omit the version-prefix, the current version of the API (v1.42) is used. For example, calling `/info` is the same as calling `/v1.42/info`. Using the API without a version-prefix is deprecated and will be removed in a future release.  Engine releases in the near future should support this version of the API, so your client will continue to work even if it is talking to a newer Engine.  The API uses an open schema model, which means server may add extra properties to responses. Likewise, the server will ignore any extra query parameters and request body properties. When you write clients, you need to ignore additional properties in responses to ensure they do not break when talking to newer daemons.   # Authentication  Authentication for registries is handled client side. The client has to send authentication details to various endpoints that need to communicate with registries, such as `POST /images/(name)/push`. These are sent as `X-Registry-Auth` header as a [base64url encoded](https://tools.ietf.org/html/rfc4648#section-5) (JSON) string with the following structure:  ``` {   \"username\": \"string\",   \"password\": \"string\",   \"email\": \"string\",   \"serveraddress\": \"string\" } ```  The `serveraddress` is a domain/IP without a protocol. Throughout this structure, double quotes are required.  If you have already got an identity token from the [`/auth` endpoint](#operation/SystemAuth), you can just pass this instead of credentials:  ``` {   \"identitytoken\": \"9cbaf023786cd7...\" } ```
 *
 * API version: 1.42
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package docker

type ContainerInspectResponse struct {
	// The ID of the container
	Id string `json:"Id,omitempty"`
	// The time the container was created
	Created string `json:"Created,omitempty"`
	// The path to the command being run
	Path string `json:"Path,omitempty"`
	// The arguments to the command being run
	Args  []string        `json:"Args,omitempty"`
	State *ContainerState `json:"State,omitempty"`
	// The container's image ID
	Image           string `json:"Image,omitempty"`
	ResolvConfPath  string `json:"ResolvConfPath,omitempty"`
	HostnamePath    string `json:"HostnamePath,omitempty"`
	HostsPath       string `json:"HostsPath,omitempty"`
	LogPath         string `json:"LogPath,omitempty"`
	Name            string `json:"Name,omitempty"`
	RestartCount    int32  `json:"RestartCount,omitempty"`
	Driver          string `json:"Driver,omitempty"`
	Platform        string `json:"Platform,omitempty"`
	MountLabel      string `json:"MountLabel,omitempty"`
	ProcessLabel    string `json:"ProcessLabel,omitempty"`
	AppArmorProfile string `json:"AppArmorProfile,omitempty"`
	// IDs of exec instances that are running in the container.
	ExecIDs     []string         `json:"ExecIDs,omitempty"`
	HostConfig  *HostConfig      `json:"HostConfig,omitempty"`
	GraphDriver *GraphDriverData `json:"GraphDriver,omitempty"`
	// The size of files that have been created or changed by this container.
	SizeRw int64 `json:"SizeRw,omitempty"`
	// The total size of all the files in this container.
	SizeRootFs      int64            `json:"SizeRootFs,omitempty"`
	Mounts          []MountPoint     `json:"Mounts,omitempty"`
	Config          *ContainerConfig `json:"Config,omitempty"`
	NetworkSettings *NetworkSettings `json:"NetworkSettings,omitempty"`
}
